from __future__ import annotations
from typing import Protocol, Optional, Iterable
from .models import ShortUrl


class ShortUrlRepository(Protocol):
    """Repository abstraction so we can swap storage without changing business logic."""
    def get(self, code: str) -> Optional[ShortUrl]: ...
    def save(self, item: ShortUrl) -> None: ...
    def exists(self, code: str) -> bool: ...
    def all(self) -> Iterable[ShortUrl]: ...
